name: factory_management_app
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  fl_chart: ^0.68.0
  intl: ^0.19.0

flutter:
  uses-material-design: true